### PR TITLE
Feature/json serializable entities

### PR DESCRIPTION
**Pull request by dimitridisko**
This is to make the lib work with a json_encode, I guess there's another way, let me know.

### CODE REVIEW

**Comment by octante** [comment]
Hi Dimitri!

Firstly thanks!! good idea!! I will try to improve it, because I think that expose all entity private variables means open excessively the api, and can not be the optimal solution if in the future we want to modify api  internal implementation. Let my try an idea please, maybe we can expose only the variables we want, adding them to this method, and avoiding get_object_vars method.

Again, thanks Dimitri! :)

**Comment by dimitridisko** [comment]
Hi, you're welcome, I'm sure you'll find a better way to do it, peace

**Comment by mmoreram** [comment]
@dimitridisko It has sense to add this kind of data inside the model if you are working using a rich-model strategy. Otherwise, if you decide to work using a rich service-layer, then you will need a service for this _transformation_.

**Comment by octante** [comment]
I'm agree, in my opinion entity don't need to know about representation. I'm trying to put this implementation in another place, service is a good choice.

Thanks @mmoreram!

**Comment by octante** [comment]
@mmoreram and @dimitridisko I have released a new tag 1.0.5 with a new service. Service name is marvel.tojson and has a unique method encode with a unique parameter, this parameter is the object returned by getResults.

I have used Serializer, a Symfony component to encode the object.

Usage example:

$charactersData = $characters
            ->getCharacters($query)
            ->getData()
            ->getResults();

$characterJSON = $this->get('marvel.tojson')->encode($character[0]);
var_dump($characterJSON);

Thank you very much to both!!

**Comment by dimitridisko** [comment]
thanks to you

**Pull request closed without merging**
